uw-ssec/tutorials

- vanitech/SciPyTutorialDescription.md
Added the SciPy tutorial description 
Tested the rse-guidelines fundamentals module to create this PR
> Added SciPy tutorial description file

- .devcontainer/Scipy2024/environment.yml
This PR adds `sentence-transformers` to the conda dependency.
> chore(deps): Add sentence-transformers dependency

- requirements.txt
Sphinx recently have new version released that's causing problem. This should help fix it.
> chore(deps): Bump sphinx version to >=7.3.6

- SciPy2024/Astro Physics Dataset Creation.ipynb
I didn't know where to put this helper code, but maybe it doesn't need to be part of the tutorial yet.
> feat: Added notebook with instructions to filter astro-ph arXiv data

- SciPy2024/module1/introduction-to-language-models.ipynb
- _toc.yml
> feat: Added a wip introduction to language models

- SciPy2024/module2/llms-and-retrieval-augmented-generation.ipynb
- _toc.yml
> feat: Added a wip notebook for olmo and rag

- resources/.gitignore
- resources/pyproject.toml
This PR setup a mini installable `ssec-tutorials` package that contains a module called `scipy_conf` where any helper code can go in here.
> feat: Add ssec-tutorials library

- intro.md
This PR redirects the home page to go directly to the SciPy tutorial
> feat: Comment out intro content and redirect to scipy for now

- SciPy2024/module3/OLMo-Chat.ipynb
- jupyter-panel-proxy.yml
Adding simple OLMo Chat Panel App example.
> feat: Add simple OLMo chat panel example

- .devcontainer/Scipy2024/devcontainer.json
This PR updates the internal package install and data download during the stage 1 and 2 after devcontainer has been created.
> chore: Update codespaces install and download during stage 1 and 2

- SciPy2024/appendix/langchain-document-loaders.ipynb
#76 
docs: add section for PyMuPdfLoader
> docs: add section for PyMuPdfLoader

- SciPy2024/module1/setup.md
This PR makes the New Codespaces button to open to new tab
> chore: Update Codespace Button to open new tab

- SciPy2024/README.md
Closes #85 and add org acknowledgements as well.
> docs: Add acknowledgement and logos

- SciPy2024/module3/2-try-with-your-data.ipynb
Anshul ran into a tiny error when he uncommented this line. Might as well make it easier on folks :)
> fix: Fix an extra close parens in module 3

- SciPy2024/module1/setup.md
Update setup instruction to include Nebari and use the `conda-lock`.
Closes #117 and the new conda-lock would hopefully also address #103
> docs: Update setup instructions

- SciPy2024/module1/2-llms-and-prompt-engineering-with-olmo.ipynb
This PR updates module 1-2 with a little more content for self-guiding
> docs: Update module 1-2 with more content

- SciPy2024/appendix/index.md
- SciPy2024/module3/2-try-with-your-data.ipynb
Updating try with your data with more explanation and steps.
> docs: Update try with your data with more steps

- SciPy2024/module2/3-retrieval-augmented-text-generation.ipynb
Update some of the content of RAG notebook to include some stuff from @vanitech PPT.
> docs: Update RAG notebook

- _toc.yml
- demos/olmo-rag/.gitattributes
- demos/olmo-rag/.gitignore
- demos/olmo-rag/index.ipynb
- demos/olmo-rag/pixi.lock
- demos/olmo-rag/pixi.toml
This PR adds an OLMO RAG Demo with pixi for running the whole thing
> feat: Add olmo rag demo

- AI_Postdoc_Workshop/README.md
- AI_Postdoc_Workshop/module1/1-llms-prompt-engineering-with-olmo.ipynb
- AI_Postdoc_Workshop/module1/2-langchain.ipynb
- AI_Postdoc_Workshop/module1/3-domain-specific-question-answering.ipynb
- AI_Postdoc_Workshop/module1/4-algorithms-prompting-with-olmo.ipynb
- AI_Postdoc_Workshop/module1/setup.md
- AI_Postdoc_Workshop/module2/1-retrieval-augmented-text-generation.ipynb
- AI_Postdoc_Workshop/module2/2-olmo-chat-rag.ipynb
Also added more algorithms questions :)
> chore: Proofreading of the AI Postdoc Workshop materials

- .devcontainer/Scipy2024/devcontainer.json
- AI_Postdoc_Workshop/module1/1-llms-prompt-engineering-with-olmo.ipynb
- AI_Postdoc_Workshop/module2/2-olmo-chat-rag.ipynb
as per #146 
* setting VSCode notebook output wordwrap setting to true by default
* Fixes Panel by opening it in new window
> fix: various repository changes for workshop

- AI_Postdoc_Workshop/module1/setup.md
> chore: Fix setup md

- AI_Postdoc_Workshop/module1/4-algorithms-prompting-with-olmo.ipynb
> Tweaks to module 1 page 4

- AI_Postdoc_Workshop/module1/setup.md
- AI_Postdoc_Workshop/module2/1-retrieval-augmented-text-generation.ipynb
- AI_Postdoc_Workshop/module2/2-olmo-chat-rag.ipynb
> fix: Reflecting feedback for 3_7 Workshop

- AI_Postdoc_Workshop/module1/2-langchain.ipynb
- AI_Postdoc_Workshop/module1/setup.md
Some small updates from going over the tutorial, no code changes.
> Minor editorial updates

- AI_For_Scientific_Discovery_Participatory_Design_Workshop/session1/index.md
Added the presentation as Iframe to render online
on the jupyterbook.
> chore: Added iframe for session 1 presentation
